<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Continue</name>
   <tag></tag>
   <elementGuidId>fcaaa929-5962-40f6-8e1a-92ca7d1f8146</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#addOrUpdateAction</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='addOrUpdateAction']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fbe5533b-61b7-45a6-828f-0c284cd83cc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>addOrUpdateAction</value>
      <webElementGuid>5864633f-17c0-475a-ac48-7adc66d74fff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui primary button bp-primary-button</value>
      <webElementGuid>91ecbe82-d2f0-4ccd-84d8-d709fd3d2dc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Continue</value>
      <webElementGuid>85698a7a-c988-463d-b967-7650d7504864</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addOrUpdateAction&quot;)</value>
      <webElementGuid>48f308f7-98c0-4149-963f-8c6c15915395</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='addOrUpdateAction']</value>
      <webElementGuid>8cfcd3c2-ae86-4343-8b79-a26eef73fabc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sign-in-container']/div/div/div/div/div[3]/button[2]</value>
      <webElementGuid>03a51b7b-e604-4248-8439-d58ba93ad49f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back'])[1]/following::button[1]</value>
      <webElementGuid>77e4f9d7-942c-4011-b47f-abdfd0de251d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forgot Password?'])[1]/following::button[2]</value>
      <webElementGuid>77123e06-4557-4c9e-8ef2-9f6c6fe7164a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'addOrUpdateAction', '&quot;', ')')])[1]/preceding::button[1]</value>
      <webElementGuid>49f481c1-ca1e-4e2b-8bb9-1f53cff68139</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Continue']/parent::*</value>
      <webElementGuid>aabdf101-c5ba-4594-bcfc-e5f69e9114ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>c33306ec-c22e-4a57-8a1f-3b73deabd86a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'addOrUpdateAction' and (text() = 'Continue' or . = 'Continue')]</value>
      <webElementGuid>e69d7877-2121-4c07-8849-f9f3144bd04a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
