<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__bp-input_1</name>
   <tag></tag>
   <elementGuidId>eb5f314c-d75f-4a95-a243-b3a127e5a8e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.bp-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0ca71850-a780-4060-a2b6-26a702dbfb8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>9a9b0ff5-93fa-47d1-afcd-b8e5fe04f5ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-key</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>4c941d65-e0c1-430a-aef5-8b4cae0050e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a20f1899-5b3d-4acc-843e-bae259386191</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-validation-type</name>
      <type>Main</type>
      <value>non_empty</value>
      <webElementGuid>edb79504-f7a4-4146-aaf2-688d38b60455</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bp-input</value>
      <webElementGuid>419d5d4b-e6ec-4d82-8711-5d4674e979de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sign-in-container&quot;)/div[@class=&quot;password&quot;]/div[@class=&quot;access-fm&quot;]/div[@class=&quot;kit-wrapper&quot;]/div[@class=&quot;ui segment&quot;]/div[@class=&quot;ui form&quot;]/div[@class=&quot;field&quot;]/input[@class=&quot;bp-input&quot;]</value>
      <webElementGuid>e412c368-5ed1-4ab8-803a-4d8cbaa628af</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='password']</value>
      <webElementGuid>2d100e63-0e8e-4081-bf8b-04431494ab75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sign-in-container']/div/div/div/div/div/div/input[2]</value>
      <webElementGuid>ebb7a40a-49d3-4a59-8bfd-312a469ab6b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>7c616bf7-22c3-49f2-8e36-422b443999ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password']</value>
      <webElementGuid>4043ad8b-083e-4a50-b458-56aacfeee220</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
