<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__bp-input</name>
   <tag></tag>
   <elementGuidId>1868dc53-c8aa-43f3-be40-fe01b0709586</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.bp-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e2b6de81-b537-4fe5-a6ac-cf9f20c52058</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1de108ba-ff9d-475d-80ce-89a6ab7944ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-key</name>
      <type>Main</type>
      <value>userName</value>
      <webElementGuid>a407eb1b-3fbe-4d48-a5aa-73f39e273230</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4261b010-dc86-4c06-8fa6-e3a1f849f4b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-validation-type</name>
      <type>Main</type>
      <value>email_id</value>
      <webElementGuid>9a624ee9-60e9-4bde-bf02-e424ff5d4c74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bp-input</value>
      <webElementGuid>eca2d05c-4671-413b-aca0-46e099476c29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sign-in-container&quot;)/div[@class=&quot;sign-in&quot;]/div[@class=&quot;access-fm&quot;]/div[@class=&quot;kit-wrapper&quot;]/div[@class=&quot;ui segment&quot;]/div[@class=&quot;ui form&quot;]/div[@class=&quot;field&quot;]/input[@class=&quot;bp-input&quot;]</value>
      <webElementGuid>10a3c65a-6463-4204-a14b-7286f4c1afbf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='text']</value>
      <webElementGuid>7caaae55-9f30-40f7-8342-921db78ee8d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sign-in-container']/div/div/div/div/div/div/input</value>
      <webElementGuid>60031475-1349-4996-9aca-c5b05930b911</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>8df134b9-aaba-4593-a66a-d0137730528f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>a90725e0-23bc-4fee-a728-58fea8baceea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
