<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__bp-input</name>
   <tag></tag>
   <elementGuidId>1868dc53-c8aa-43f3-be40-fe01b0709586</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.bp-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a22c9278-dc52-49ec-9059-4335f31005ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ad236568-5629-434e-acd4-3fb83c5fdfba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-key</name>
      <type>Main</type>
      <value>userName</value>
      <webElementGuid>463c329e-17b7-495c-8da8-017b1eaa7d34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>515657c7-c802-442e-be90-46bc71dda2dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-validation-type</name>
      <type>Main</type>
      <value>email_id</value>
      <webElementGuid>46471749-febc-42f1-89ec-0bb89ffc19ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bp-input</value>
      <webElementGuid>2e7c0383-572d-4089-b1a7-97579fd89a16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sign-in-container&quot;)/div[@class=&quot;sign-in&quot;]/div[@class=&quot;access-fm&quot;]/div[@class=&quot;kit-wrapper&quot;]/div[@class=&quot;ui segment&quot;]/div[@class=&quot;ui form&quot;]/div[@class=&quot;field&quot;]/input[@class=&quot;bp-input&quot;]</value>
      <webElementGuid>e04410e7-e426-4d0b-bb17-dc1a0c24eb87</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='text']</value>
      <webElementGuid>777875f3-736b-4177-b7c9-cf8c3fa2938d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sign-in-container']/div/div/div/div/div/div/input</value>
      <webElementGuid>2d44e317-9348-40ed-ba62-c24b745c0fb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>7969d7c2-ba0f-41ab-a148-3df34ee870d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>f5b2e74e-a69a-473d-b57f-2b9f3440874c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
