<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Sindhuja</name>
   <tag></tag>
   <elementGuidId>9d677450-9436-4bbd-a9be-bba5c42d5b0b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.person-name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='profile-dropdown']/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>68bc9289-8e8d-4c45-a261-cc80ae1849d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>person-name</value>
      <webElementGuid>5bb858ab-5edb-4e0a-921a-dbcc88e85b6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sindhuja</value>
      <webElementGuid>08b556c6-9353-46ab-9873-7a3ea98775f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;profile-dropdown&quot;)/div[@class=&quot;ui dropdown button bp-dropdown&quot;]/span[@class=&quot;person-name&quot;]</value>
      <webElementGuid>339b8084-e286-4fff-957b-b3f074bea9dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='profile-dropdown']/div/span</value>
      <webElementGuid>c8e7768f-1876-47e5-8319-68cba52ccbd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Backflipt'])[2]/following::span[1]</value>
      <webElementGuid>b9eb72e2-575d-4063-a883-f693bbad3aec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Update profile'])[1]/preceding::span[1]</value>
      <webElementGuid>41ca3e9b-d3ca-43f9-b876-d40416f87989</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Change password'])[1]/preceding::span[1]</value>
      <webElementGuid>e4e52594-dd20-4007-aa97-b0212e6deb07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sindhuja']/parent::*</value>
      <webElementGuid>1b2c7ea7-7df8-4410-b493-fbeca0536ede</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span</value>
      <webElementGuid>96878ce6-c10d-4b25-842b-2cb95c4a3694</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Sindhuja' or . = 'Sindhuja')]</value>
      <webElementGuid>19f15b88-9e8c-4890-9762-dd5139c4e012</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
